[libraries]
annotation = "androidx.annotation:annotation:1.2.0"
core = "androidx.core:core-ktx:1.7.0"
appcompat = "androidx.appcompat:appcompat:1.3.1"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.1"
material = "com.google.android.material:material:1.4.0"
lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1"
coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.1"
viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
livedata = "androidx.lifecycle:lifecycle-livedata-ktx:2.4.0"
activity-ktx = "androidx.activity:activity-ktx:1.4.0"
fragment-ktx = "androidx.fragment:fragment-ktx:1.3.6"

# test
junit = "junit:junit:4.13.2"
mockk = "io.mockk:mockk:1.12.0"
android-test = "androidx.test.ext:junit:1.1.3"
espresso = "androidx.test.espresso:espresso-core:3.4.0"

[plugins]
android-app = "com.android.application:7.2.0-beta02"
android-lib = "com.android.library:7.2.0-beta02"
